[package]
name = "parser"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
node.workspace = true
thiserror.workspace = true
macro_deserialize.workspace = true

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.26.1"
